### ISSUE TITLE
Wrapper/Video/OCVCamera+Private.h:11:9: 'opencv2/videoio/cap_ios.h' file not found

### ISSUE THREAD

**Issue by anonym24** [Legoless/LegoCV#5]
When building the project I get this error
`Wrapper/Video/OCVCamera+Private.h:11:9: 'opencv2/videoio/cap_ios.h' file not found`

I downloaded opencv, put it there:

![screenshot_2](https://user-images.githubusercontent.com/8851301/32778457-a101a05e-c942-11e7-9552-3a5b152b71e2.png)
![screenshot_1](https://user-images.githubusercontent.com/8851301/32778458-a1205fa8-c942-11e7-8fd5-ced583d43a02.png)

added opencv to Frameworks in XCode

**Comment by anonym24** [comment]
I also tried with a new project and `Podfile`

```
target 'opencv'
       pod 'LegoCV'
```

`pod install`

but I get next error with opencv (as I understand it tried to build it, but failed)

```
nstalling LegoCV (0.1.0)
Installing OpenCV-Dynamic (3.2.4)
[!] /bin/bash -c 
set -e
git submodule init
git submodule update
python opencv/platforms/ios/build_framework.py ios --dynamic
cp -a ./ios/opencv2.framework ./opencv2.framework

Submodule path 'opencv': checked out 'a8aff6f64330a0ab2c9d71033412af892dd9b710'
Submodule 'opencv' (https://github.com/opencv/opencv.git) registered for path 'opencv'
Cloning into '/Users/admin/Library/Caches/CocoaPods/Pods/Release/OpenCV-Dynamic/3.2.4-8d4c9/opencv'...
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
============================================================
ERROR: Command '['xcodebuild', '-version']' returned non-zero exit status 1
============================================================
Traceback (most recent call last):
  File "opencv/platforms/ios/build_framework.py", line 112, in build
    self._build(outdir)
  File "opencv/platforms/ios/build_framework.py", line 80, in _build
    xcode_ver = getXCodeMajor()
  File "opencv/platforms/ios/build_framework.py", line 41, in getXCodeMajor
    ret = check_output(["xcodebuild", "-version"])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['xcodebuild', '-version']' returned non-zero exit status 1

```

**Comment by anonym24** [comment]
fixes with https://github.com/nodejs/node-gyp/issues/569#issuecomment-94917337

opencv was built ok

```
Installing LegoCV (0.1.0)
Installing OpenCV-Dynamic (3.2.4)
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `opencv.xcworkspace` for this project from now on.
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 2 total pods installed.
```

**Comment by anonym24** [comment]
`use_frameworks!` added it also so I could import LegoCV pod to the project

but some classes still undefined:

![screenshot_5](https://user-images.githubusercontent.com/8851301/32889115-36edc774-cad2-11e7-823c-caddf78ca925.png)

**Comment by anonym24** [comment]
solved I needed to add opencv 2 framework file to a project and haar xml cascade file


but now I meet next problem https://github.com/Legoless/LegoCV/issues/8
